apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster
  region: ap-south-1
nodeGroups:
  - name: ClusterNG
    desiredCapacity: 2
    instanceType: t2.micro
    ssh:
        publicKeyName: ck
