kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: efs-provisioner/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
       storage: 4Gi
